TaskManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('main.urls')),
    path('task/', include('task.urls')),
    path('users/', include('users.urls'))
]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
]

task/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.main, name='task_dashboard'),
    path('create/', views.task_create, name="task_create"),
    path('returned/', views.returned_task, name="task_returned"),
    path('base/<int:task_id>', views.task, name="base"),
    path('base/<int:id>/<int:actions>', views.action),
    path('correct_task/', views.corrections_task, name='correct_task')
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', views.logout_user, name='logout'),
    
]

main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from task.models import task_state


class Task(models.Model):
    objects = None
    name = models.CharField('Название задачи', max_length=100)
    executor = models.ForeignKey(User, default="1", on_delete=models.CASCADE, related_name='executor')
    descriptions = models.TextField('Описание задачи')
    date = models.DateTimeField('Дата публикации', default=timezone.now)
    author = models.ForeignKey(User, default="1", on_delete=models.CASCADE, related_name='Автор')
    state = models.ForeignKey(task_state, default="1", on_delete=models.CASCADE, related_name='Состояние')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Задачу'
        verbose_name_plural = 'Задачи'

task/models.py
from django.db import models


class task_state(models.Model):
    objects = None
    name = models.CharField('Состояние', max_length=100)
    meta_info = models.CharField('Мета-информация', max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Состояние'
        verbose_name_plural = 'Состояния задач'

users/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Permission(models.Model):

    permission = models.TextField('Право')

    def __str__(self):
        return self.permission

    class Meta:
        verbose_name = 'Право'
        verbose_name_plural = 'Права'


class UserPermissions(models.Model):
    object = None
    permission = models.ForeignKey(Permission, on_delete=models.CASCADE, related_name='Право')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='Пользователь')

    def __str__(self):
        names = f'{self.user} - {self.permission}'
        return names

    class Meta:
        verbose_name = 'Наследование'
        verbose_name_plural = 'Наследование прав'

main/forms.py
from .models import Task

task/forms.py
from django.forms import ModelForm, TextInput, DateTimeInput
from main.models import Task


class TaskRegisterForm(ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'descriptions', 'executor', 'author', 'state']

        widgets={
            'name': TextInput(attrs={
                'class': '',

            }),
            'descriptions': TextInput(attrs={
                'class': '',

            })
        }

users/forms.py
from django.forms import TextInput, EmailInput, PasswordInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        password = TextInput
        widgets = {
            "username": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'name@example.com',
            }),
            "email": EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'name@example.com',
            }),
            "password1": PasswordInput(attrs={
                'class': 'form-control',
                'placeholder': 'name@example.com',
            }),
            "password2": PasswordInput(attrs={
                'class': 'form-control',
                'placeholder': 'name@example.com',
            })

        }

main/views.py
from django.shortcuts import render
from .models import Task
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def index(request):
    task = Task.objects.filter(state="4", author=request.user.id)
    return render(request, 'main/dashboard.html', {'task': task})

task/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages
from main.models import Task
from task.forms import TaskRegisterForm
from api.task import getTask
from api.task import BaseTaskState
from task.models import task_state
from api.generic import getButtons
from api.task import getCorrectionsTask


@login_required
def main(request):
    page = 'task_dashboard'
    return render(request, 'task/index.html', getTask(request, page))

@login_required
def returned_task(request):
    return render(request, 'task/returned.html', getTask(request, 'returned_task'))


@login_required
def task_create(request):
    if request.method == 'POST':
        form = TaskRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('task_dashboard')
    form = TaskRegisterForm()
    perm = BaseTaskState(request)
    return render(request, 'task/create.html', {'form': form, 'perm': perm})


def task(request, task_id):
    state = getButtons(task_id)
    meta = Task.objects.filter(id=task_id)
    return render(request, 'task/meta.html', {'task': meta, 'states': state})


def action(request, id, actions):
    task = Task.objects.get(id=id)
    task.state = task_state.objects.get(id=actions)
    task.save(update_fields=["state"])
    return redirect(f'/task/base/{id}')


def corrections_task(request):
    return render(request, 'task/corrections_task.html', getCorrectionsTask(request))

users/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.shortcuts import render

from .forms import UserRegisterForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Создан аккаунт {username}!')
            return redirect('index')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


def profile():
    pass


def logout_user(request):
    logout(request)
    return redirect('/')

main/templates/main/dashboard.html
{% extends "main/base_layer.html" %}
{% block title %}Главная - DP{% endblock %}
{% block content %}
<div>
    {% if task %}
     <h2 class="bs-title">Задачи требующие вашего внимания:</h2>
    {% endif %}
   
    {% for tas in task %}
        <div class='card'>
            <div class='card-header'>
                <h5 class="">{{ tas.author }} —> {{ tas.executor }}
                </h5>
            </div>
            <div class="card-body">
                <h5 class="card-title">
                    {{ tas.name }} - {{ tas.state }}
                </h5>
                <p class='text-warning'>
                    {{ tas.date }}
                </p>
            </div>
        </div>
	{% endfor %}
</div>
{% endblock %}

task/templates/task/corrections_task.html
{% extends "main/base_layer.html" %}
{% block title %}Корректировки - DP{% endblock %}
{% block css %}
.scrolling {
width: 99hw;
overflow-x: scroll;
overflow-y: scroll;
}
{% endblock %}
{% block content %}
<main>
    <h2>Задачи которые вы можете откорректировать: </h2>
    <div class='scrolling'>
        <table class="table">
            <tr>
                <td>ID</td>
                <td>Название</td>
                <td>Исполнитель</td>
                <td>Дата</td>
                <td>Состояние</td>
            </tr>
            {% for first in first %}
            <tr>
                <td><a href="/task/base/{{ first.id }}">{{ first.id }}</a></td>
                <td>{{ first.name }}</td>
                <td>{{ first.executor }}</td>
                <td>{{ first.date }}</td>
                <td>{{ first.state }}</td>
            </tr>
            {% endfor %}

        </table>
    </div>

    <h2>Запрошенные корректировки</h2>
    <div class='scrolling'>
        <table class="table">
            <tr>
                <td>ID</td>
                <td>Название</td>
                <td>Исполнитель</td>
                <td>Дата</td>
                <td>Состояние</td>
            </tr>
            {% for second in second %}
            <tr>
                <td>{{ second.id }}</td>
                <td>{{ second.name }}</td>
                <td>{{ second.executor }}</td>
                <td>{{ second.date }}</td>
                <td>{{ second.state }}</td>
            </tr>
            {% endfor %}

        </table>
    </div>
</main>
{% endblock %}

task/templates/task/create.html
{% extends "main/base_layer.html" %}
{% block css %}
html,
body {
  height: 100%;
}

.form-signin {
  max-width: 330px;
  padding: 1rem;
}

.form-signin .form-floating:focus-within {
  z-index: 2;
}

.form-signin input[type="text"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
{% endblock %}
{% block title%}Вход - DP {% endblock %}
{% block content %}
<main class="form-signin">
    <form method="post">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Создание задачи</h1>
        <div class="form-floating">
            <input type="text" class="form-control" name="name" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_name">
            <label for="id_username">Название задачи</label>
        </div>
        <div class="form-floating">
            <input type="text" name="descriptions"  required="" id="id_descriptions" class="form-control" placeholder="Описание">
            <label for="id_password">Описание задачи</label>
        </div>
        <div class="form-floating">
            {{ form.executor }}
            <input type="hidden" id="ud_author" name="author" value="{{ user.id }}">
            <input type="hidden" id="id_state" name="state" value="{{ perm }}">
        </div>
        <button class="btn btn-primary w-100 py-2" type="submit">Создать</button>
    </form>
</main>
{% endblock content %}

task/templates/task/index.html
{% extends "main/base_layer.html" %}
{% block title %}Задачи - DP{% endblock %}
{% block css %}
.scrolling {
width: 99hw;
overflow-x: scroll; 
overflow-y: scroll; 
}
{% endblock %}
{% block content %}
<main>
    <div class='navbar'>
        <a class="text-decoration-none" href="{% url 'task_create' %} ">
            <button class="btn btn-outline-primary">
                Создать задачу
            </button>
        </a>
        <a class="text-decoration-none" href="{% url 'correct_task' %} ">
            <button class="btn btn-outline-primary">
                Корректировки
            </button>
        </a>
        <a class="text-decoration-none" href="{% url 'task_returned' %} ">
            <button class="btn btn-outline-primary">
                Возвраты
            </button>
        </a>
    </div>
    <div class='scrolling'>
        <table class="table">
            <tr>
                <td>ID</td>
                <td>Название</td>
                <td>Исполнитель</td>
                <td>Дата</td>
                <td>Состояние</td>
            </tr>
            {% for tas in task %}
            <tr>
                
                <td><a href="/task/base/{{ tas.id }}">{{ tas.id }}</a></td>
                <td>{{ tas.name }}</td>
                <td>{{ tas.executor }}</td>
                <td>{{ tas.date }}</td>
                <td>{{ tas.state }}</td>
            </tr>
            {% endfor %}
            
        </table>
    </div>
</main>
{% endblock %}
            <input type="text" id="id_author" value="{{ user.id }}">
            <input type="text" id="id_state" value="{{ perm }}">

task/templates/task/meta.html
{% extends "main/base_layer.html" %}
{% block title %}Задача  - DP{% endblock %}
{% block content %}
<main>    {% for tas in task %}
        <div class='card'>
            <div class='card-header'>
                <h5 class="">{{ tas.author }} —> {{ tas.executor }}
                </h5>
            </div>
            <div class="card-body">
                <h5 class="card-title">
                    {{ tas.name }} - {{ tas.state }}
                </h5>
                <p class='text-warning'>
                    {{ tas.date }}
                </p>
                <p class='text'>
                    {{ tas.descriptions }}
                </p>

            </div>
        </div>


    <div class="navbar">
        {% for state in states %}
        <button class="btn btn-outline-primary">
            <a class="text-decoration-none" href="/task/base/{{ tas.id }}/{{ state.id }}">{{ state.name }}</a>
        </button>
        {% endfor %}
    </div>

    {% endfor %}

</main>
{% endblock %}
  

task/templates/task/page.html
{{ form }}

task/templates/task/returned.html
{% extends "main/base_layer.html" %}
{% block title %}Возвраты - DP{% endblock %}
{% block css %}
.scrolling {
width: 99hw;
overflow-x: scroll; 
overflow-y: scroll; 
}
{% endblock %}
{% block content %}
<main>
    <div class='scrolling'>
        <table class="table">
            <tr>
                <td>ID</td>
                <td>Название</td>
                <td>Исполнитель</td>
                <td>Дата</td>
                <td>Состояние</td>
            </tr>
            {% for tas in task %}
            <tr>
                <td><a href="/task/base/{{ tas.id }}">{{ tas.id }}</a></td>
                <td>{{ tas.name }}</td>
                <td>{{ tas.executor }}</td>
                <td>{{ tas.date }}</td>
                <td>{{ tas.state }}</td>
            </tr>
            {% endfor %}
            
        </table>
    </div>
</main>
{% endblock %}
  

users/templates/users/login.html
{% extends "main/base_layer.html" %}
{% block css %}
html,
body {
  height: 100%;
}

.form-signin {
  max-width: 330px;
  padding: 1rem;
}

.form-signin .form-floating:focus-within {
  z-index: 2;
}

.form-signin input[type="text"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
{% endblock %}
{% block title%}Вход - DP {% endblock %}
{% block content %}
<main class="form-signin ">
    <form method="post">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Вход в DP:TaskManager</h1>
        <div class="form-floating">
            <input type="text" class="form-control" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">
            <label for="id_username">Имя пользователя</label>
        </div>
        <div class="form-floating">
            <input type="password" name="password" autocomplete="current-password" required="" id="id_password" class="form-control" placeholder="Password">
            <label for="id_password">Пароль</label>
        </div>
        <button class="btn btn-primary w-100 py-2" type="submit">Войти</button>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Нужен аккаунт? <a class="ml-2" href="{% url 'register' %}">Регистрация</a>
        </small>
    </div>
</main>
{% endblock content %}

users/templates/users/logout.html
{% extends "main/lay.html" %}
{% block content %}
    <h2>Вы вышли из своей учётной записи</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Войти</a>
        </small>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends "main/base_layer.html" %}

{% block css %}
    html,
    body {
      height: 100%;
    }

    .form-signin {
      max-width: 330px;
      padding: 1rem;
    }

    .form-signin .form-floating:focus-within {
      z-index: 2;
    }

    .form-signin input[name="email"] {
      margin-bottom: -1px;
      border-bottom-right-radius: 0;
      border-bottom-left-radius: 0;
    }

    .form-signin input[name="username"] {
      margin-bottom: -1px;
      border-bottom-right-radius: 0;
      border-bottom-left-radius: 0;
      border-top-left-radius: 0;
      border-top-right-radius: 0;
    }

    .form-floating input[name="password1"] {
      margin-bottom: -1px;
      width: 298px;
      border-bottom-right-radius: 0;
      border-bottom-left-radius: 0;
      border-top-left-radius: 0;
      border-top-right-radius: 0;
      max-width: 330px;
      padding: 1rem;
      display: block;
      font-size: 1rem;
      font-weight: 400;
      line-height: 1.5;
      color: #212529;
      background-color: #fff;
      background-clip: padding-box;
      border: 1px solid #ced4da;
      -webkit-appearance: none;
      -moz-appearance: none;
      appearance: none;
      transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
    }

    .form-signin input[name="password2"] {
      margin-bottom: -1px;
      width: 298px;
      border-bottom-right-radius: 0.375rem;
      border-bottom-left-radius: 0.375rem;
      border-top-left-radius: 0;
      border-top-right-radius: 0;
      max-width: 330px;
      padding: 1rem;
      display: block;
      font-size: 1rem;
      font-weight: 400;
      line-height: 1.5;
      color: #212529;
      background-color: #fff;
      background-clip: padding-box;
      border: 1px solid #ced4da;
      -webkit-appearance: none;
      -moz-appearance: none;
      appearance: none;
      transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
    }

    .b-example-divider {
      width: 100%;
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }
    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
      --bd-violet-bg: #712cf9;
      --bd-violet-rgb: 112.520718, 44.062154, 249.437846;
      --bs-btn-font-weight: 600;
      --bs-btn-color: var(--bs-white);
      --bs-btn-bg: var(--bd-violet-bg);
      --bs-btn-border-color: var(--bd-violet-bg);
      --bs-btn-hover-color: var(--bs-white);
      --bs-btn-hover-bg: #6528e0;
      --bs-btn-hover-border-color: #6528e0;
      --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
      --bs-btn-active-color: var(--bs-btn-hover-color);
      --bs-btn-active-bg: #5a23c8;
      --bs-btn-active-border-color: #5a23c8;
    }

    .bd-mode-toggle {
      z-index: 1500;
    }

    .bd-mode-toggle .dropdown-menu .active .bi {
      display: block !important;
    }
{% endblock %}

{% block title %}Регистрация - DP{% endblock %}

{% block content %}

<main class="form-signin">
    <form method="POST">
        <h1 class="h3 mb-3 fw-normal">Регистрация пользователя в системе</h1>
        {% csrf_token %}
        <div class="form-floating">
            {{ form.email }}
            <label for="email">Email</label>
        </div>
        <div class="form-floating">
            {{ form.username }}
            <label for="email">Имя пользователя</label>
        </div>
        <div class="form-floating">
            {{ form.password1 }}
            <label for="id_password1">Пароль</label>
        </div>
        <div class="form-floating">
            {{ form.password2 }}
            <label for="id_password2">Повторите пароль</label>
        </div>
        <br>

        <button class="btn btn-primary w-100 py-2" type="submit">Зарегистрироваться</button>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Уже есть аккаунт? <a class="ml-2" href="{% url 'login'%}">Вход</a>
        </small>
    </div>
</main>

{% endblock %}